// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/brawlers.proto

package brawlers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BrawlerService_GetBrawlersInfo_FullMethodName   = "/brawlers.BrawlerService/GetBrawlersInfo"
	BrawlerService_GetBrawlerList_FullMethodName    = "/brawlers.BrawlerService/GetBrawlerList"
	BrawlerService_AddBrawler_FullMethodName        = "/brawlers.BrawlerService/AddBrawler"
	BrawlerService_GetBrawlerByTyppe_FullMethodName = "/brawlers.BrawlerService/GetBrawlerByTyppe"
)

// BrawlerServiceClient is the client API for BrawlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrawlerServiceClient interface {
	GetBrawlersInfo(ctx context.Context, in *BrawlerRequest, opts ...grpc.CallOption) (*BrawlerResponse, error)
	GetBrawlerList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrawlerResponse], error)
	AddBrawler(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewBrawlerRequest, AddBrawlerResponse], error)
	GetBrawlerByTyppe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BrawlerTyppeRequest, BrawlerResponse], error)
}

type brawlerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrawlerServiceClient(cc grpc.ClientConnInterface) BrawlerServiceClient {
	return &brawlerServiceClient{cc}
}

func (c *brawlerServiceClient) GetBrawlersInfo(ctx context.Context, in *BrawlerRequest, opts ...grpc.CallOption) (*BrawlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrawlerResponse)
	err := c.cc.Invoke(ctx, BrawlerService_GetBrawlersInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brawlerServiceClient) GetBrawlerList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BrawlerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrawlerService_ServiceDesc.Streams[0], BrawlerService_GetBrawlerList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, BrawlerResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrawlerService_GetBrawlerListClient = grpc.ServerStreamingClient[BrawlerResponse]

func (c *brawlerServiceClient) AddBrawler(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewBrawlerRequest, AddBrawlerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrawlerService_ServiceDesc.Streams[1], BrawlerService_AddBrawler_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NewBrawlerRequest, AddBrawlerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrawlerService_AddBrawlerClient = grpc.ClientStreamingClient[NewBrawlerRequest, AddBrawlerResponse]

func (c *brawlerServiceClient) GetBrawlerByTyppe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BrawlerTyppeRequest, BrawlerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BrawlerService_ServiceDesc.Streams[2], BrawlerService_GetBrawlerByTyppe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BrawlerTyppeRequest, BrawlerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrawlerService_GetBrawlerByTyppeClient = grpc.BidiStreamingClient[BrawlerTyppeRequest, BrawlerResponse]

// BrawlerServiceServer is the server API for BrawlerService service.
// All implementations must embed UnimplementedBrawlerServiceServer
// for forward compatibility.
type BrawlerServiceServer interface {
	GetBrawlersInfo(context.Context, *BrawlerRequest) (*BrawlerResponse, error)
	GetBrawlerList(*Empty, grpc.ServerStreamingServer[BrawlerResponse]) error
	AddBrawler(grpc.ClientStreamingServer[NewBrawlerRequest, AddBrawlerResponse]) error
	GetBrawlerByTyppe(grpc.BidiStreamingServer[BrawlerTyppeRequest, BrawlerResponse]) error
	mustEmbedUnimplementedBrawlerServiceServer()
}

// UnimplementedBrawlerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBrawlerServiceServer struct{}

func (UnimplementedBrawlerServiceServer) GetBrawlersInfo(context.Context, *BrawlerRequest) (*BrawlerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrawlersInfo not implemented")
}
func (UnimplementedBrawlerServiceServer) GetBrawlerList(*Empty, grpc.ServerStreamingServer[BrawlerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetBrawlerList not implemented")
}
func (UnimplementedBrawlerServiceServer) AddBrawler(grpc.ClientStreamingServer[NewBrawlerRequest, AddBrawlerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AddBrawler not implemented")
}
func (UnimplementedBrawlerServiceServer) GetBrawlerByTyppe(grpc.BidiStreamingServer[BrawlerTyppeRequest, BrawlerResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetBrawlerByTyppe not implemented")
}
func (UnimplementedBrawlerServiceServer) mustEmbedUnimplementedBrawlerServiceServer() {}
func (UnimplementedBrawlerServiceServer) testEmbeddedByValue()                        {}

// UnsafeBrawlerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrawlerServiceServer will
// result in compilation errors.
type UnsafeBrawlerServiceServer interface {
	mustEmbedUnimplementedBrawlerServiceServer()
}

func RegisterBrawlerServiceServer(s grpc.ServiceRegistrar, srv BrawlerServiceServer) {
	// If the following call pancis, it indicates UnimplementedBrawlerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BrawlerService_ServiceDesc, srv)
}

func _BrawlerService_GetBrawlersInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrawlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrawlerServiceServer).GetBrawlersInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BrawlerService_GetBrawlersInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrawlerServiceServer).GetBrawlersInfo(ctx, req.(*BrawlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrawlerService_GetBrawlerList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrawlerServiceServer).GetBrawlerList(m, &grpc.GenericServerStream[Empty, BrawlerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrawlerService_GetBrawlerListServer = grpc.ServerStreamingServer[BrawlerResponse]

func _BrawlerService_AddBrawler_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrawlerServiceServer).AddBrawler(&grpc.GenericServerStream[NewBrawlerRequest, AddBrawlerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrawlerService_AddBrawlerServer = grpc.ClientStreamingServer[NewBrawlerRequest, AddBrawlerResponse]

func _BrawlerService_GetBrawlerByTyppe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BrawlerServiceServer).GetBrawlerByTyppe(&grpc.GenericServerStream[BrawlerTyppeRequest, BrawlerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BrawlerService_GetBrawlerByTyppeServer = grpc.BidiStreamingServer[BrawlerTyppeRequest, BrawlerResponse]

// BrawlerService_ServiceDesc is the grpc.ServiceDesc for BrawlerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrawlerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brawlers.BrawlerService",
	HandlerType: (*BrawlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBrawlersInfo",
			Handler:    _BrawlerService_GetBrawlersInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBrawlerList",
			Handler:       _BrawlerService_GetBrawlerList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddBrawler",
			Handler:       _BrawlerService_AddBrawler_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetBrawlerByTyppe",
			Handler:       _BrawlerService_GetBrawlerByTyppe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/brawlers.proto",
}
