// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: proto/brawlers.proto

package brawlers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrawlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // Cambiado a CamelCase
}

func (x *BrawlerRequest) Reset() {
	*x = BrawlerRequest{}
	mi := &file_proto_brawlers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrawlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrawlerRequest) ProtoMessage() {}

func (x *BrawlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brawlers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrawlerRequest.ProtoReflect.Descriptor instead.
func (*BrawlerRequest) Descriptor() ([]byte, []int) {
	return file_proto_brawlers_proto_rawDescGZIP(), []int{0}
}

func (x *BrawlerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BrawlerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // Cambiado a CamelCase
	Type     string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"` // Cambiado a CamelCase
}

func (x *BrawlerResponse) Reset() {
	*x = BrawlerResponse{}
	mi := &file_proto_brawlers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrawlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrawlerResponse) ProtoMessage() {}

func (x *BrawlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brawlers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrawlerResponse.ProtoReflect.Descriptor instead.
func (*BrawlerResponse) Descriptor() ([]byte, []int) {
	return file_proto_brawlers_proto_rawDescGZIP(), []int{1}
}

func (x *BrawlerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrawlerResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BrawlerResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type NewBrawlerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // Cambiado a CamelCase
	Type     string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"` // Cambiado a CamelCase
}

func (x *NewBrawlerRequest) Reset() {
	*x = NewBrawlerRequest{}
	mi := &file_proto_brawlers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBrawlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBrawlerRequest) ProtoMessage() {}

func (x *NewBrawlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brawlers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBrawlerRequest.ProtoReflect.Descriptor instead.
func (*NewBrawlerRequest) Descriptor() ([]byte, []int) {
	return file_proto_brawlers_proto_rawDescGZIP(), []int{2}
}

func (x *NewBrawlerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewBrawlerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NewBrawlerRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type AddBrawlerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *AddBrawlerResponse) Reset() {
	*x = AddBrawlerResponse{}
	mi := &file_proto_brawlers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBrawlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBrawlerResponse) ProtoMessage() {}

func (x *AddBrawlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brawlers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBrawlerResponse.ProtoReflect.Descriptor instead.
func (*AddBrawlerResponse) Descriptor() ([]byte, []int) {
	return file_proto_brawlers_proto_rawDescGZIP(), []int{3}
}

func (x *AddBrawlerResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_brawlers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brawlers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_brawlers_proto_rawDescGZIP(), []int{4}
}

type BrawlerTyppeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *BrawlerTyppeRequest) Reset() {
	*x = BrawlerTyppeRequest{}
	mi := &file_proto_brawlers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrawlerTyppeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrawlerTyppeRequest) ProtoMessage() {}

func (x *BrawlerTyppeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brawlers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrawlerTyppeRequest.ProtoReflect.Descriptor instead.
func (*BrawlerTyppeRequest) Descriptor() ([]byte, []int) {
	return file_proto_brawlers_proto_rawDescGZIP(), []int{5}
}

func (x *BrawlerTyppeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_proto_brawlers_proto protoreflect.FileDescriptor

var file_proto_brawlers_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73,
	0x22, 0x24, 0x0a, 0x0e, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x55, 0x0a, 0x0f, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x57, 0x0a,
	0x11, 0x4e, 0x65, 0x77, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x2a, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x42, 0x72, 0x61,
	0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x29, 0x0a, 0x13, 0x42,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x32, 0xb6, 0x02, 0x0a, 0x0e, 0x42, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x62,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x73, 0x2e, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x0f, 0x2e, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e,
	0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x49, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x12,
	0x1b, 0x2e, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x4e, 0x65, 0x77, 0x42, 0x72,
	0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x51, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x42, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x42, 0x79, 0x54, 0x79, 0x70, 0x70,
	0x65, 0x12, 0x1d, 0x2e, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x72, 0x61,
	0x77, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x2e, 0x42, 0x72, 0x61, 0x77,
	0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x1b, 0x5a, 0x19, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x62, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_brawlers_proto_rawDescOnce sync.Once
	file_proto_brawlers_proto_rawDescData = file_proto_brawlers_proto_rawDesc
)

func file_proto_brawlers_proto_rawDescGZIP() []byte {
	file_proto_brawlers_proto_rawDescOnce.Do(func() {
		file_proto_brawlers_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_brawlers_proto_rawDescData)
	})
	return file_proto_brawlers_proto_rawDescData
}

var file_proto_brawlers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_brawlers_proto_goTypes = []any{
	(*BrawlerRequest)(nil),      // 0: brawlers.BrawlerRequest
	(*BrawlerResponse)(nil),     // 1: brawlers.BrawlerResponse
	(*NewBrawlerRequest)(nil),   // 2: brawlers.NewBrawlerRequest
	(*AddBrawlerResponse)(nil),  // 3: brawlers.AddBrawlerResponse
	(*Empty)(nil),               // 4: brawlers.Empty
	(*BrawlerTyppeRequest)(nil), // 5: brawlers.BrawlerTyppeRequest
}
var file_proto_brawlers_proto_depIdxs = []int32{
	0, // 0: brawlers.BrawlerService.GetBrawlersInfo:input_type -> brawlers.BrawlerRequest
	4, // 1: brawlers.BrawlerService.GetBrawlerList:input_type -> brawlers.Empty
	2, // 2: brawlers.BrawlerService.AddBrawler:input_type -> brawlers.NewBrawlerRequest
	5, // 3: brawlers.BrawlerService.GetBrawlerByTyppe:input_type -> brawlers.BrawlerTyppeRequest
	1, // 4: brawlers.BrawlerService.GetBrawlersInfo:output_type -> brawlers.BrawlerResponse
	1, // 5: brawlers.BrawlerService.GetBrawlerList:output_type -> brawlers.BrawlerResponse
	3, // 6: brawlers.BrawlerService.AddBrawler:output_type -> brawlers.AddBrawlerResponse
	1, // 7: brawlers.BrawlerService.GetBrawlerByTyppe:output_type -> brawlers.BrawlerResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_brawlers_proto_init() }
func file_proto_brawlers_proto_init() {
	if File_proto_brawlers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_brawlers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brawlers_proto_goTypes,
		DependencyIndexes: file_proto_brawlers_proto_depIdxs,
		MessageInfos:      file_proto_brawlers_proto_msgTypes,
	}.Build()
	File_proto_brawlers_proto = out.File
	file_proto_brawlers_proto_rawDesc = nil
	file_proto_brawlers_proto_goTypes = nil
	file_proto_brawlers_proto_depIdxs = nil
}
